# ============================================================
# Streamlit App Configuration - SINASC & APGAR5 Project
# ============================================================

[theme]
primaryColor = "#006d77"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
address = "0.0.0.0"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"
